### ISSUE TITLE
make `m3gnet` optional dependency (?)

### ISSUE THREAD

**Issue by kjappelbaum** [sparks-baird/xtal2png#116]
as it is an option for decoding and can make issues when installing it might make sense to have it as 

```
[options.extras_require]
   m3gnet = m3gnet
```

**Comment by kjappelbaum** [comment]
looking at the code in this part, I'd consider moving things into their own function to keep the main class a bit slimmer and easier to read. 

For instance, https://github.com/sparks-baird/xtal2png/blob/1f5d4b9773102104f72cde6eae2d089c011a8a55/src/xtal2png/core.py#L969-L987 could be its own function, which would also make it easier to write smaller unit tests. 

For https://github.com/sparks-baird/xtal2png/blob/1f5d4b9773102104f72cde6eae2d089c011a8a55/src/xtal2png/core.py#L1017-L1019 I'd consider wrapping it into a context manager, such that the restore also happens if there is an exception in the code above.

**Comment by sgbaird** [comment]
> as it is an option for decoding and can make issues when installing it might make sense to have it as
> 
> ```
> [options.extras_require]
>    m3gnet = m3gnet
> ```

I'll give this one some more thought. Having it as a default seemed appealing from the perspective of defaults being production options. Part of that's a selfish desire that people don't use it with sub-par parameters when benchmarking or comparing it against other things. However, it is an optional post-processing step in that the encoding and decoding of `xtal2png` can take place without it, and tensorflow is a non-negligible extra dep. Any extra thoughts here?

> looking at the code in this part, I'd consider moving things into their own function to keep the main class a bit slimmer and easier to read.
> 
> For instance,
> 
> https://github.com/sparks-baird/xtal2png/blob/1f5d4b9773102104f72cde6eae2d089c011a8a55/src/xtal2png/core.py#L969-L987
> 
> could be its own function, which would also make it easier to write smaller unit tests.

Agreed that the main class could be refactored to be slimmer. I started playing with code around the section you mentioned and had some trouble finding a satisfactory refactor. Definitely, something I'll keep in mind going forward. Also, some of the code there isn't flexible enough in its current state to handle the shape-changing hyperparameters mentioned in #109, hence trying to prioritize which hyperparameters seem like they'd maximize the improvement-to-cost ratio during generative modeling in a sort of [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) frame of mind.

> For
> 
> https://github.com/sparks-baird/xtal2png/blob/1f5d4b9773102104f72cde6eae2d089c011a8a55/src/xtal2png/core.py#L1017-L1019
> 
> I'd consider wrapping it into a context manager, such that the restore also happens if there is an exception in the code above.

I should have removed this in https://github.com/sparks-baird/xtal2png/commit/1eadcc11ce289d7389a39e31c5d32f08fac38ad6. Thanks for pointing out.
