### ISSUE TITLE
`func:` syntax issue in API docs

### ISSUE THREAD

**Issue by sgbaird** [sparks-baird/xtal2png#149]
e.g. https://xtal2png.readthedocs.io/en/latest/api/xtal2png.html#xtal2png.core.XtalConverter

![image](https://user-images.githubusercontent.com/45469701/177737843-22a4abab-fc29-4e5d-8289-170eba9fd4aa.png)

**Comment by kjappelbaum** [comment]
a find-replace with `:func` -> `:py:func:` should fix it (?)

**Comment by sgbaird** [comment]
@kjappelbaum thanks! Looks like I had the right syntax in some places but left some stragglers. The reminder of the correct syntax (`:func:`) was useful. I've had trouble remembering that one.
