### ISSUE TITLE
Add `element-coder` to `conda-forge`

### ISSUE THREAD

**Issue by sgbaird** [sparks-baird/xtal2png#174]
https://conda-forge.org/docs/maintainer/adding_pkgs.html

https://github.com/kjappelbaum/element-coder/issues/13

**Comment by kjappelbaum** [comment]
https://github.com/conda-forge/staged-recipes/pull/19628

**Comment by kjappelbaum** [comment]
currently trying to get some of the `element-coder` dependencies to `conda-forge`....

**Comment by kjappelbaum** [comment]
done https://github.com/conda-forge/element-coder-feedstock
