### ISSUE TITLE
Any acknowledgements that need to be added to `paper.md`?

### ISSUE THREAD

**Issue by sgbaird** [sparks-baird/xtal2png#193]
@kjappelbaum (e.g. grant award number)

**Comment by sgbaird** [comment]
@cseeg @hasan-sayeed @michaeldalverson

https://github.com/sparks-baird/xtal2png/blob/main/reports/paper.md#acknowledgements

**Comment by sp8rks** [comment]
Those acknowledgements are fine by me.

**Comment by sgbaird** [comment]
@sp8rks do we acknowledge ReUSE? Also, not sure if the topological insulators grant should be acknowledged for Hasan.

**Comment by sp8rks** [comment]
You are right! Please acknowledge both.

**Comment by sgbaird** [comment]
@cseeg and @hasan-sayeed, will you each make a PR adding the appropriate statement to the acknowledgments section?

**Comment by sgbaird** [comment]
https://github.com/sparks-baird/xtal2png/pull/197
