### ISSUE TITLE
consider kwarg for mapping noble gases to a "nearby" element or (better) using different elemental featurizer

### ISSUE THREAD

**Issue by sgbaird** [sparks-baird/xtal2png#82]
e.g. $He \rightarrow H\space\mathrm{or}\space Li$

Issue with generated structures having noble gases might be helped by:
- #81

**Comment by kjappelbaum** [comment]
I do not know if you already investigated this, but sometimes it tends to help to not encode atomic numbers but something that is closely related to chemistry (and varying with a more consistent trend across the PTE) such as the electronegativity. 

Maybe one could give the user the option to specify any `Element` property as the encoding of the "chemistry" of a given site. It could default to the atomic number but in this way, you can easily switch to `X`, `electron_affinity`, or whatever. 

If you want me to make a PR for that, simply assign me to this issue.

**Comment by sgbaird** [comment]
That would be great! The [modified Pettifor scale](https://iopscience.iop.org/article/10.1088/1367-2630/18/9/093011/meta) is one that I considered, mostly based on prior experience with [ElMD](https://github.com/lrcfmd/ElMD) (see e.g. [`mat_discover`](https://github.com/sparks-baird/mat_discover)). I like the idea of using an `Element` property to keep it flexible.

**Comment by kjappelbaum** [comment]
Since I ended up writing the same code in different packages, I started collecting it in [`element-coder`](https://github.com/kjappelbaum/element-coder).

**Comment by sgbaird** [comment]
@kjappelbaum is `element-coder` in a state that it can be incorporated into `xtal2png`?

**Comment by kjappelbaum** [comment]
I think so - I use it already in one of my other projects. I was waiting for the `fit` but then got distracted by other things. Will give it a stab this WE!

**Comment by sgbaird** [comment]
Ok, cool! Not sure if you saw, `fit` is implemented now #91, though some of the decisions I made on how to set it up were somewhat arbitrary. Lmk if you think something should change with that approach.

Thank you! I appreciate you getting involved despite many other priorities I'm sure

**Comment by sgbaird** [comment]
See https://github.com/sparks-baird/xtal2png/blob/09e26f55e9dd12cb5a3fd4831df77b90b845eb3b/src/xtal2png/core.py#L303 in particular (small refactor about to pull into main in https://github.com/sparks-baird/xtal2png/pull/112)

**Comment by kjappelbaum** [comment]
at least for regression, the encoding makes a *huge* difference: Here on a MOF dataset, showing top-100-in-top-100 (greater is better), contrasting the mod. Pettifor with electronegativity.

I'm not using the `xtal2png` for this plot but revised autocorrelation functions, but wouldn't be surprised to also see an impact here.  
<img width="396" alt="Screen Shot 2022-06-20 at 20 52 48" src="https://user-images.githubusercontent.com/32935233/174663070-ad9d3dfc-bebd-45f1-9ee8-7f6db883eefd.png">

**Comment by sgbaird** [comment]
@kjappelbaum this weekend I'm planning to try doing a distributed hyperparameter optimization on my uni's HPC via RayTune. Getting RayTune and Slurm to play nicely together might take some time (my first time connecting the two), but my goal is to at least get a dummy run operating. Two hyperparameters that I think would be really important to have for the full run (which might not happen until next week) are the elemental encodings and lexicographic site sorting (#75).

**Comment by kjappelbaum** [comment]
ok, the PR is anyhow close to being done. I'll finish it tomorrow morning

**Comment by kjappelbaum** [comment]
But also looking forward to seeing the RayTune + Slurm code 👍🏽

**Comment by sgbaird** [comment]
> ok, the PR is anyhow close to being done. I'll finish it tomorrow morning

Awesome, I just took a closer look at the changes and am seeing that now.



> But also looking forward to seeing the RayTune + Slurm code 👍🏽

Sounds good! I hope I don't disappoint haha
