### ISSUE TITLE
Consider using Wyckoff positions instead of atomic sites

### ISSUE THREAD

**Issue by sgbaird** [sparks-baird/xtal2png#94]
Almost always fewer than the total number of sites, e.g. [mp-19841](https://materialsproject.org/materials/mp-19841), [mp-500](https://materialsproject.org/materials/mp-500), [mp-19770](https://materialsproject.org/materials/mp-19770). Would cut down the dimensionality by a significant amount, though it also introduces the possibility of representations that aren't able to be reconstructed (disregarding whether the structure would be realistic or not). See e.g. [pyxtal: checking compatibility](https://pyxtal.readthedocs.io/en/latest/Algorithm.html#checking-compatibility). There's also the question of how to numerically encode the Wyckoff position types. Might be worth digging more into Wren's representation https://github.com/CompRhys/aviary.

**Comment by sgbaird** [comment]
Asymmetric unit cell == primitive unit cell, meaning the minimum # of Wyckoff sites that let you reproduce the full unit cell IIUC.

**Comment by sgbaird** [comment]
https://github.com/sparks-baird/xtal2png/pull/97

**Comment by sgbaird** [comment]
Related methods from CDVAE (emphasis added):
> There are infinitely many different ways of choosing the lattice for the same material. We **compute the Niggli reduced lattice (Grosse-Kunstleve et al., 2004) with pymatgen** (Ong et al., 2013), which is a unique lattice for any given material. Since the lattice matrix L is not rotation invariant, we instead predict the 6 lattice parameters, i.e. the lengths of the 3 lattice vectors and the angles between them. **We normalize the lengths of lattice vectors with [N^(1/3)]**, where N is the number of atoms, to ensure that the lengths for materials of different sizes are at the same scale.

See [`get_reduced_structure()`](https://pymatgen.org/pymatgen.core.structure.html#pymatgen.core.structure.IStructure.get_reduced_structure)

**Comment by kjappelbaum** [comment]
> disregarding whether the structure would be realistic or not

I think this would be an interesting thing to analyze at some point - does symmetrization lead to more "realistic" structures. My intuition is that, on average, this is the case
